name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            python3-pip \
            python3-setuptools \
            python3-setuptools-git \
            python3-wheel \
            python3-cython \
            python3-numpy \
            python3-pygments \
            python3-yaml \
            python3-six \
            libmtdev-dev \
            libjpeg-dev \
            libavformat-dev \
            libswscale-dev \
            libavdevice-dev \
            libavutil-dev \
            libavcodec-dev \
            libavfilter-dev \
            libswresample-dev \
            libpostproc-dev \
            libmtdev-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libsdl2-image-dev \
            libsdl2-dev \
            pkg-config \
            libgstreamer1.0-dev \
            git \
            cython

      - name: Install buildozer
        run: |
          git clone https://github.com/kivy/buildozer.git
          cd buildozer
          sudo python3 setup.py install

      - name: Build APK
        run: |
          buildozer init
          buildozer -v android debug

